/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.badini.translate;

public final class R {
  public static final class color {
    public static final int ic_launcher_background=0x7f010000;
    public static final int ic_launcher_foreground=0x7f010001;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f020000;
    public static final int ic_launcher_round=0x7f020001;
  }
  public static final class string {
    public static final int app_name=0x7f030000;
    public static final int btn_translate=0x7f030001;
    public static final int copy_hint=0x7f030002;
    public static final int label_from=0x7f030003;
    public static final int label_to=0x7f030004;
    public static final int label_translation=0x7f030005;
    public static final int translate_hint=0x7f030006;
    public static final int untranslated_warning=0x7f030007;
    public static final int word_details=0x7f030008;
  }
  public static final class style {
    public static final int Theme_BadiniTranslate=0x7f040000;
  }
}